CREATE TABLE fauna_vertebrae (
	X FLOAT8,
	Y FLOAT8,
	OBJECTID INT,
	SUBURB VARCHAR,
	PROP_NAME VARCHAR,
	GI_CLASS VARCHAR,
	GI_TYPE VARCHAR,
	GROUP_ VARCHAR,
	FAMILY VARCHAR,
	FAM_COM VARCHAR,
	SCI_NAME VARCHAR,
	GENUS VARCHAR,
	SPECIES VARCHAR,
	COM_NAME VARCHAR,
	STATUS VARCHAR
);

SELECT * FROM fauna_vertebrae;